version: '2'

services:
  nginx:
    restart: always
    image: nginx:alpine
    network_mode: host
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./htpasswd:/etc/nginx/htpasswd
      - ./dhparam.pem:/etc/nginx/dhparam.pem
      - ./ssl_params:/etc/nginx/ssl_params
      - walklog_public:/usr/share/nginx/walk.asharpminor.com
      - asharpminor.com:/usr/share/nginx/asharpminor.com
      - /home/sugi/apps/mastodon/public:/usr/share/nginx/mstdn.asharpminor.com
      - letsencrypt:/etc/letsencrypt
      - ./logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webhook
  webhook:
    restart: always
    build: webhook
    volumes:
      - /home/sugi/apps/asharpminor.com:/src
      - asharpminor.com:/output
    ports:
      - "127.0.0.1:18889:18889"
  certbot:
    image: adamant/alpine-certbot
    volumes:
      - letsencrypt:/etc/letsencrypt

volumes:
  asharpminor.com: {}
  walklog_public:
    external: true
  letsencrypt: {}
